# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'MLBench '
tagline:          'Distributed Machine Learning Benchmark'
description:      'A public and reproducible collection of reference implementations and benchmark suite for <u>distributed machine learning</u> algorithms, frameworks and systems.'
url:              http://mlbench.github.io
baseurl:          'https://mlbench.github.io/'

paginate:         5
paginate_path:    "/blog/page:num/"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mlbench/mlbench

markdown: kramdown

kramdown: 
  toc_levels: 1..2 
